### ISSUE TITLE
Branding and visuals

### ISSUE THREAD

**Issue by tonin** [perfsonar/psgui#23]
It would be nice to have, before the first beta release, some kind of branding, even minimalist, with mention of the GÉANT and perfSONAR projects and logos. Maybe also an "About…" page with links to the source code and this issue tracker.

**Comment by tonin** [comment]
If we add an "About…" page, it would be useful that this page contains at least the following links:
- perfsonar.net website and logo
- hosted by GÉANT with logo and link to geant.org
- PMP MaDDash to get access to the historical measurement and status of the different hosts
- this GitHub issue tracker so users know how to submit bugs and feature requests,

**Comment by ljhr** [comment]
Since there was an empty Home page branding and visuals were added there
