### ISSUE TITLE
Display test parameters on result page

### ISSUE THREAD

**Issue by tonin** [perfsonar/psgui#25]
It would be useful to have the parameters used for the test displayed again on the result page, at the side, bottom or in a pop-up. It is sometimes hard to remember exactly which parameters were used when using the custom ones (and also to show to the user what the defaults were).

**Comment by ljhr** [comment]
I've added a layer to show custom parameters on the results page. Default ones are not chosen by user and they are not part of the pscheduler results (JSON) so it is not possible to display them here.
