### ISSUE TITLE
Throughput interval labels when using Omit Interval

### ISSUE THREAD

**Issue by tonin** [perfsonar/psgui#27]
When running a throughput test using the `Omit Interval` advanced parameter, the first labels are a bit misleading, looking like a repetition.  Maybe a better option would be to label the intervals omitted with negative numbers.  See attached as example:

<img width="819" alt="Capture d’écran 2022-10-10 à 14 32 18" src="https://user-images.githubusercontent.com/484879/194890885-78bf00d6-bb97-4586-9d9a-246c873667ab.png">

**Comment by ljhr** [comment]
Resolved - packets omitted instead of being shown with repeating numbers
